# Generated by Django 3.0.3 on 2020-07-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpost',
        ),
    ]
