# Generated by Django 3.0.3 on 2020-05-30 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200408_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
